### ISSUE TITLE
Question: does LMDB / LMDB-js track the last time an entry was read

### ISSUE THREAD

**Issue by kylebernhardy** [kriszyp/lmdb-js#135]
Was wondering if the LRU tracks the last time an entry was read

**Comment by kriszyp** [comment]
Are you wondering if the cache could store the last time an entry was accessed? Or actually persisting last time stamp in the database? Would this be to check if it is fresh? If in the cache, I think you could probably do something like this:
```
import { LRFUExpirer } from 'weak-lru-cache'
class LRFUExpirerWithTime extends LRFUExpirer {
  used(entry, expirationPriority) {
    entry.lastAccess = Date.now();
    super.used(entry, expirationPriority);
  }
}
let myExpirer = LRFUExpirerWithTime();
let db = open(path, {
  cache: { expirer: myExpirer }
});
db.getEntry(key).lastAccess
```
I could add that as an option, but I think this seems reasonably extendable.

**Comment by kylebernhardy** [comment]
I was curious if there was a lower level inspecting, possible at the base LMDB layer that had some insight into a last read time of an entry. Also knowing you have an LRU implementation wanted to see if there was anything exposed or possible to track a LR time ephemerally.  I think it would be too much overhead for us to directly write LR time to the db.

**Comment by kriszyp** [comment]
No, I don't think there would be any lower level tracking of last access time. Get operations are pretty side-effect free. Seems like the closest thing to an access time would be the OS's tracking of active (vs standby or uncached) pages, but that is hidden/inaccessible to user/non-kernel code as far as a I know. And yes, writing to database on every read sounds pretty expensive. The best idea I have for getting information about the last read time of recently read entries would be the code suggestion above.

**Comment by kylebernhardy** [comment]
Thank you Kris,

I do like the option you provided, would this entail work on your end?  If so there is no urgency to accommodating this feature.

**Comment by kriszyp** [comment]
The code sample above was something I believe should work with lmdb-js as is. You would just be extending the cache expirer, which I think is the best way to do this, and wouldn't require any changes on my side to lmdb-js. Are you currently using lmdb-js's caching? Would it be safe to assume you would just be doing this for the main database and not the (dupSort) indices? And are you using `childTransaction` at all (that is currently incompatible with caching)?

**Comment by kylebernhardy** [comment]
We are not currently using caching, but I have been thinking on adding it in a future release this year.  This extension would give more richness to the addition.  I would just be adding it to the primary, non-dupsorted, db.  For reads we do not currently use child transactions, would this be possible in the future?

**Comment by kriszyp** [comment]
Yes, I would like to add support for using child transactions with caching in the future (main issue is that child transactions can be aborted, so need a way to rollback entries that were cached in the txn).

**Comment by kriszyp** [comment]
I realized I hadn't followed up here. Support for caching with child transactions was added in v2.3 (#137).

And I've been thinking that there might be a means of efficiently updating a last access timestamp with direct writes, if that is helpful. But we will probably some time to talk more about that in the future :).
