### ISSUE TITLE
doesExist returns false after put with cache enabled

### ISSUE THREAD

**Issue by KyleAMathews** [kriszyp/lmdb-js#210]
I assumed that `doesExist` would work with in-flight puts but apparently not? It'd be convenient to support both in-flight + synced.

```typescript
import * as lmdb from "lmdb";
let store = lmdb.open("cache", {
  name: "cache",
  cache: true,
});

async function main() {
  console.log(store.doesExist("x"));
  console.log(store.get("x"));
  store.put("x", Buffer.from(""));
  console.log(store.doesExist("x"));
  console.log(store.get("x"));
}

main();
```

**Comment by kriszyp** [comment]
Good catch, thanks for the report. Committed a fix, will publish soon.

BTW, congratulations on the Netlify deal! Really happy for you and the team!

**Comment by KyleAMathews** [comment]
Thanks!
