### ISSUE TITLE
doesExist ambiguous?

### ISSUE THREAD

**Issue by anywhichway** [kriszyp/lmdb-js#213]
The doc below seems ambiguous. What if the value at the key is a number?

db.doesExist(key, valueOrVersion): boolean

This checks if an entry exists for the given key, and optionally verifies that the version or value exists. If this is a dupSort enabled database, you can provide the key and value to check if that key/value entry exists. If you are using a versioned database, you can provide a version number to verify if the entry for the provided key has the specific version number. This returns true if the entry does exist.

**Comment by kriszyp** [comment]
Keys can be numbers, so if you use doesExist with a just a number and no second argument, it will return if there is an entry with that key.
```
db.putSync(42, {});
db.doesExist(42) -> true
db.doesExist(43) -> false
```

**Comment by kriszyp** [comment]
If you have versioning enabled, it will treat the second argument as a version. So `db.doesExist("a",1)` would be true for the first example and `db.doesExist("a",2);` for the second.

**Comment by anywhichway** [comment]
Thank you.
