### ISSUE TITLE
copy data folder to new server

### ISSUE THREAD

**Issue by morteza102030** [kriszyp/lmdb-js#256]
i copy data folder to new server now my app get error and don't run 

**Segmentation fault (core dumped)**

**Comment by kriszyp** [comment]
If you are attempting to copy files while they are in use (while writes are taking place) with a typical file system copy command, this will result in indetermistic copying of pages from different transactions and leads to database corruption if you try to open the target file. LMDB has a specific function to support snapshot based backup of a database to a target file. I added docs for this here:
https://github.com/kriszyp/lmdb-js#dbbackuppath-promise
