### ISSUE TITLE
bug(binary): `binary` store does not guarantee a `Buffer` on `get`

### ISSUE THREAD

**Issue by dtfiedler** [kriszyp/lmdb-js#262]
Environment:
- `NodeJS`: `18.17.1`
- `lmdb`: `2.8.5`

Example:
```
// index.mjs
import { open } from 'lmdb';

const lmdb = open({
    path: '/data/lmdb',
    encoding: 'binary',
});

const responseObject = await fetch('https://arweave.net/block/height/800079'); // large JSON object
const bigJsonObject = await responseObject.json();

await lmdb.put('my-buffer', Buffer.from(JSON.stringify(bigJsonObject), 'base64'));

const object = lmdb.get('my-buffer');
console.log(object instanceof Uint8Array); // true
console.log(object instanceof Buffer); // false
const isBuffer = Buffer.isBuffer(object); // false
```
Expectations:
- When we retrieving an `Buffer` object via `get` - a `Buffer` is always returned; in this example, a `Uint8Array` is returned causing issues downstreams when working with the response

We believe the reason is due to [this line](https://github.com/kriszyp/lmdb-js/blob/4c3a3b9eb590a876a923e0f9818d698ee0fccb2f/read.js#L232), where `Buffers` can be casted to `Uint8Arrays`  under the hood.

As a workaround we explicitly check that we are returned a `Buffer` and if not, create one from the returned object:
```
const potentialBuffer = lmdb.get(key) 
if (potentialBuffer) {
  return Buffer.from(value.buffer);
}
```

**Comment by kriszyp** [comment]
This should be addressed in v2.9, I believe.
